#! /usr/bin/perl

use strict;
use Cwd;
use File::Spec;

BEGIN {
  $^W = 1;  # Use warnings
  my $curdir = File::Spec->canonpath( Cwd::cwd() );
  unless ($curdir eq '/Users/jmac/volity/cvs/games-perl/eights') {
    die ('This script must be run from /Users/jmac/volity/cvs/games-perl/eights, not '."$curdir\n".
	 "Please re-run the Build.PL script here.\n");
  }
  @INC = 
    (
     '/sw/lib/perl5',
     '/sw/lib/perl5',
     '/System/Library/Perl/5.8.1/darwin-thread-multi-2level',
     '/System/Library/Perl/5.8.1',
     '/Library/Perl/5.8.1/darwin-thread-multi-2level',
     '/Library/Perl/5.8.1',
     '/Library/Perl',
     '/Network/Library/Perl/5.8.1/darwin-thread-multi-2level',
     '/Network/Library/Perl/5.8.1',
     '/Network/Library/Perl',
     '/Users/jmac/volity/cvs/games-perl/eights'
    );
}

use Module::Build;

if (-e 'Build.PL' and not Module::Build->up_to_date("Build.PL", $0)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.\n";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = Module::Build->resume (
  properties => {
    config_dir => '/Users/jmac/volity/cvs/games-perl/eights/_build',
  },
);

$build->dispatch;
